filebeat.inputs:
  - type: filestream
    id: docker-containers
    enabled: true

    paths:
      - /var/lib/docker/containers/*/*.log

    parsers:
      - container:
          stream: all
          format: docker

    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata: ~

setup.template.enabled: true
setup.template.name: "goflow"
setup.template.pattern: "goflow-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "goflow-%{+yyyy.MM.dd}"

logging.level: info